version : '3.8'

services:
  db:
    image: mysql
    container_name: Person_App
    ports:
      - 3306:3306
    volumes:
      - "./data.sql:/docker-entrypoint-initdb.d/data.sql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root